### ISSUE TITLE
I am getting this warning on packaging. Can you please check this one

### ISSUE THREAD

**Issue by Sardorian** [feixuwu/UnrealEngine4-EZ-Mobile-Ads#1]
UATHelper: Packaging (Android (Multi:ASTC,PVRTC,DXT,ATC,ETC2,ETC1)): UnrealBuildTool: D:\Unreal Ngine\prjcts\Migrated 4.17\Plugins\AdCollection\Source\AdCollection\AdCollection.Build.cs: warning: Module constructors should take a ReadOnlyTargetRules argument (rather than a TargetInfo argument) and pass it to the base class constructor from 4.15 onwards. Plea
se update the method signature.
UATHelper: Packaging (Android (Multi:ASTC,PVRTC,DXT,ATC,ETC2,ETC1)): UnrealBuildTool: D:\Unreal Ngine\prjcts\Migrated 4.17\Plugins\AdCollection\Source\AdCollectionEditor\AdCollectionEditor.Build.cs: warning: Module constructors should take a ReadOnlyTargetRules argument (rather than a TargetInfo argument) and pass it to the base class constructor from 4.15 o
nwards. Please update the method signature.
UATHelper: Packaging (Android (Multi:ASTC,PVRTC,DXT,ATC,ETC2,ETC1)): UnrealBuildTool: D:\Unreal Ngine\prjcts\Migrated 4.17\Plugins\AdCollection\Source\AdMob\AdMob.Build.cs: warning: Module constructors should take a ReadOnlyTargetRules argument (rather than a TargetInfo argument) and pass it to the base class constructor from 4.15 onwards. Please update the 
method signature.
UATHelper: Packaging (Android (Multi:ASTC,PVRTC,DXT,ATC,ETC2,ETC1)): UnrealBuildTool: D:\Unreal Ngine\prjcts\Migrated 4.17\Plugins\AdCollection\Source\ChartBoost\ChartBoost.Build.cs: warning: Module constructors should take a ReadOnlyTargetRules argument (rather than a TargetInfo argument) and pass it to the base class constructor from 4.15 onwards. Please u
pdate the method signature.
UATHelper: Packaging (Android (Multi:ASTC,PVRTC,DXT,ATC,ETC2,ETC1)): UnrealBuildTool: D:\Unreal Ngine\prjcts\Migrated 4.17\Plugins\AdCollection\Source\Unity\Unity.Build.cs: warning: Module constructors should take a ReadOnlyTargetRules argument (rather than a TargetInfo argument) and pass it to the base class constructor from 4.15 onwards. Please update the 
method signature.
UATHelper: Packaging (Android (Multi:ASTC,PVRTC,DXT,ATC,ETC2,ETC1)): UnrealBuildTool: D:\Unreal Ngine\prjcts\Migrated 4.17\Plugins\AdCollection\Source\Vungle\Vungle.Build.cs: warning: Module constructors should take a ReadOnlyTargetRules argument (rather than a TargetInfo argument) and pass it to the base class constructor from 4.15 onwards. Please update th
e method signature.

**Comment by feixuwu** [comment]
It should be fine,  the plugin current support 4.15, 
the unreal engine 4  build system changed since 4.16, so if you build the plugin with 4.16 and 4.17 will
 show the warning, but the build will success.

when the 4.18 released, I will update the build.cs to only support 4.16 4.17 and 4.18, then the  warning will dissappear.
