### ISSUE TITLE
Vungle library not found

### ISSUE THREAD

**Issue by AT-MAK** [feixuwu/UnrealEngine4-EZ-Mobile-Ads#10]
Hi there I have an issue here with UE 4.18.3 and building for ios. Everything works perfectly with remote build but i get the warning with the following error:

UATHelper: Packaging (iOS):   ld: warning: directory not found for option '-LD:/MYGAME/Plugins/AdCollection/Source/AdMob/../AdCollection/ThirdPartyFrameworks/VungleAdmobIOS/'
UATHelper: Packaging (iOS):  
UATHelper: Packaging (iOS):   ld: library not found for -lVungleAdapter

Please help. Your plugin works perfectly with my android version. I do not even need vungle, just the other networks. Thank you

**Comment by feixuwu** [comment]
I will check it later this week, I remember removed vungle...
there must be some thing wrong,  did you tried my demo project on ios?

?? Outlook for Android<https://aka.ms/ghei36>

________________________________
