### ISSUE TITLE
On iOS.. level starts while ad is playing

### ISSUE THREAD

**Issue by Sim-fo** [feixuwu/UnrealEngine4-EZ-Mobile-Ads#11]
Hello. In my iOS game I use node "show interstitials" before "open level". But there is a problem - the level starts while ad is playing. How can I start the level automatically after the advertisement has been closed? In android version of my game, everything works fine. The level starts after interstitials ad is closed.

**Comment by feixuwu** [comment]
I think it is not a good idea show interstitial before load level,
on ios, you may consider call show interstitial after load level?

**Comment by feixuwu** [comment]
yes, maybe add an ads close event will make things more easy,
I will add this feature next days.

**Comment by Sim-fo** [comment]
Thank you so much!

**Comment by Sim-fo** [comment]
Thank you!
