### ISSUE TITLE
Compiling error Android build

### ISSUE THREAD

**Issue by Kiborgik** [feixuwu/UnrealEngine4-EZ-Mobile-Ads#12]
**Fix:**
```
-#include "ModuleManager.h"
+#include "Modules/ModuleManager.h"
```

**Comment by Kiborgik** [comment]
> which engine version build use?

4.20.3

**Comment by feixuwu** [comment]
it should not happen, the package should success, did u build from engine source?
I will do more test.

**Comment by Kiborgik** [comment]
> it should not happen, the package should success, did u build from engine source?
> I will do more test.

i found this bug when i connected Unit ads
and found this
[ https://github.com/gameDNAstudio/MobileUtils/commit/82619599f9d3ab172238afdddcae3a12d5fc6feb]( https://github.com/gameDNAstudio/MobileUtils/commit/82619599f9d3ab172238afdddcae3a12d5fc6feb)

**Comment by feixuwu** [comment]
I packaged for android full rebuild with 4.20.3 and there's no build fail.
anyway, if u package success, it's fine.

**Comment by Kiborgik** [comment]
> I packaged for android full rebuild with 4.20.3 and there's no build fail.
> anyway, if u package success, it's fine.

sry, i forgot about: Blueprints Nativization Inclusive

**Comment by feixuwu** [comment]
thanks very much, I test with blueprint nativization and found the problem.
and fix just as you said.
