### ISSUE TITLE
Work only 2 ads in the example project

### ISSUE THREAD

**Issue by FynjyAC** [feixuwu/UnrealEngine4-EZ-Mobile-Ads#14]
![1mc8nnruv2w](https://user-images.githubusercontent.com/10727336/49522212-357f3480-f8b8-11e8-80e8-267ff518920f.jpg)

**Comment by feixuwu** [comment]
facebook and admob may not work in all country or region,
u may use vpn in america to test the ads

**Comment by FynjyAC** [comment]
I tested in different regions. VPN did not help.

After hundreds of different attempts, I was able to run. Only Shiping and apk work with admob. If I run from the editor - the problem remains.
I think the problem is in the Google Play policy.

**Comment by FynjyAC** [comment]
I mean "launch on device" from editor.
