### ISSUE TITLE
What is the 4.19 compatible version?

### ISSUE THREAD

**Issue by MrGoatsy** [feixuwu/UnrealEngine4-EZ-Mobile-Ads#16]
I can't find it in the previous commits.

**Comment by feixuwu** [comment]
you can check it in commits, before I submit 4.20 support

**Comment by MrGoatsy** [comment]
I tried to install them but it requires me to rebuild the a few files.

After doing that the plugin doesn't show up in my plugin folder as can be seen here:
https://i.imgur.com/iVMm0bP.png

**Comment by feixuwu** [comment]
please use the 4.19 branch
https://github.com/feixuwu/UnrealEngine4-EZ-Mobile-Ads/tree/4.19
