### ISSUE TITLE
Plugin Package Error

### ISSUE THREAD

**Issue by kerds78** [feixuwu/UnrealEngine4-EZ-Mobile-Ads#20]
I tried packaging the plugin individually after having issues caused by iOS builds, and I got this error:

> ActionThread.ActionDebugOutput: 1 warning generated.
> ActionThread.ThreadFunc: [11/21] Compile Module.AdCollection.gen.cpp
> ActionThread.ThreadFunc: [12/21] Compile Module.AdCollection.cpp
> UnrealBuildTool.Main: CompilationResultException: Error: OtherCompilationError
> UnrealBuildTool.Main:   at UnrealBuildTool.ActionGraph.ExecuteActions (UnrealBuildTool.BuildConfiguration BuildConfiguration, System.Collections.Generic.List`1[T] ActionsToExecute) [0x000a5] in <fa92783b56d7408392bffe459f68bb68>:0 
> UnrealBuildTool.Main:   at UnrealBuildTool.BuildMode.Build (System.Collections.Generic.List`1[T] TargetDescriptors, UnrealBuildTool.BuildConfiguration BuildConfiguration, UnrealBuildTool.ISourceFileWorkingSet WorkingSet, UnrealBuildTool.BuildOptions Options) [0x00235] in <fa92783b56d7408392bffe459f68bb68>:0 
> UnrealBuildTool.Main:   at UnrealBuildTool.BuildMode.Execute (Tools.DotNETCommon.CommandLineArguments Arguments) [0x002cc] in <fa92783b56d7408392bffe459f68bb68>:0 
> UnrealBuildTool.Main:   at UnrealBuildTool.UnrealBuildTool.Main (System.String[] ArgumentsArray) [0x00291] in <fa92783b56d7408392bffe459f68bb68>:0
> Timeline.Print: Timeline:
> Timeline.Print: 
> Timeline.Print: [ 0.000]
> Timeline.Print: [ 0.000](+0.183) <unknown>
> Timeline.Print: [ 0.183](+0.004) FileMetadataPrefetch.QueueEngineDirectory()
> Timeline.Print: [ 0.188](+0.289) XmlConfig.ReadConfigFiles()
> Timeline.Print: [ 0.477](+0.000) SingleInstanceMutex.Acquire()
> Timeline.Print: [ 0.477](+0.158) UEBuildPlatform.RegisterPlatforms()
> Timeline.Print:   0.479          [ 0.002](+0.105) Initializing InstalledPlatformInfo
> Timeline.Print:   0.584          [ 0.107](+0.000) Querying types
> Timeline.Print:   0.586          [ 0.108](+0.007) MacPlatformFactory
> Timeline.Print:   0.593          [ 0.116](+0.003) TVOSPlatformFactory
> Timeline.Print:   0.597          [ 0.120](+0.031) AndroidPlatformFactory
> Timeline.Print:   0.628          [ 0.151](+0.001) IOSPlatformFactory
> Timeline.Print:   0.629          [ 0.152](+0.002) HTML5PlatformFactory
> Timeline.Print:   0.632          [ 0.155](+0.000) LinuxPlatformFactory
> Timeline.Print:   0.632          [ 0.155](+0.002) LuminPlatformFactory
> Timeline.Print:   0.635          [ 0.158](+0.000) WindowsPlatformFactory
> Timeline.Print: [ 0.640](+0.009) TargetDescriptor.ParseCommandLine()
> Timeline.Print: [ 0.652](+4.842) UEBuildTarget.Create()
> Timeline.Print:   0.653          [ 0.000](+3.032) RulesCompiler.CreateTargetRulesAssembly()
> Timeline.Print:   0.653            0.000          [ 0.000](+2.803) <unknown>
> Timeline.Print:   3.457            2.804          [ 2.803](+0.082) Finding engine modules
> Timeline.Print:   3.540            2.887          [ 2.886](+0.005) Finding plugin modules
> Timeline.Print:   3.545            2.892          [ 2.891](+0.092) <unknown>
> Timeline.Print:   3.638            2.985          [ 2.984](+0.016) Finding program modules
> Timeline.Print:   3.655            3.002          [ 3.001](+0.001) Finding program targets
> Timeline.Print:   3.656            3.003          [ 3.002](+0.029) <unknown>
> Timeline.Print:   3.685          [ 3.033](+0.099) RulesAssembly.CreateTargetRules()
> Timeline.Print:   3.798          [ 3.145](+0.204) UEBuildTarget constructor
> Timeline.Print:   3.804            3.151          [ 0.006](+0.197) Reading source file metadata cache
> Timeline.Print:   4.002          [ 3.350](+1.492) UEBuildTarget.PreBuildSetup()
> Timeline.Print: [ 5.496](+24.795) UEBuildTarget.Build()
> Timeline.Print:   5.496          [ 0.000](+0.021) <unknown>
> Timeline.Print:   5.518          [ 0.021](+0.713) ExternalExecution.SetupUObjectModules()
> Timeline.Print:   6.232          [ 0.735](+0.170) <unknown>
> Timeline.Print:   6.402          [ 0.905](+11.266) Executing UnrealHeaderTool
> Timeline.Print:  17.670          [12.173](+0.001) ExternalExecution.ResetCachedHeaderInfo()
> Timeline.Print:  17.672          [12.175](+0.396) ExternalExecution.UpdateDirectoryTimestamps()
> Timeline.Print:  18.069          [12.572](+11.679) UEBuildBinary.Build()
> Timeline.Print:  29.748          [24.251](+0.544) <unknown>
> Timeline.Print: [30.304](+0.002) Reading dependency cache
> Timeline.Print: [30.307](+0.001) Reading action history
> Timeline.Print: [30.309](+0.025) ActionGraph.GetActionsToExecute()
> Timeline.Print:  30.309          [ 0.000](+0.009) Prefetching include dependencies
> Timeline.Print:  30.319          [ 0.010](+0.015) Cache outdated actions
> Timeline.Print: [30.335](+0.029) <unknown>
> Timeline.Print: [30.364](+76.419) ActionGraph.ExecuteActions()
> Timeline.Print: [106.784](+0.205) <unknown>
> Timeline.Print: [106.989](+0.000) FileMetadataPrefetch.Stop()
> Timeline.Print: [106.991]

I am using a mac with UE 4.22.1

**Comment by feixuwu** [comment]
hi, sorry for my delay, would u please post the full error message?

**Comment by kerds78** [comment]
Oh, you solved my issue here: https://forums.unrealengine.com/development-discussion/ios-development/1622573-ios-packaging-error-on-mac
