### ISSUE TITLE
Unreal android package fail

### ISSUE THREAD

**Issue by okanerenli** [feixuwu/UnrealEngine4-EZ-Mobile-Ads#21]
====14.06.2019 12:50:04====PREPARING NATIVE CODE=================================================================
UATHelper: Packaging (Android (ETC2)): On build machine.
UATHelper: Packaging (Android (ETC2)): Fixing minSdkVersion; NDK level above 19 requires minSdkVersion of 21 (arch=arm64)
UATHelper: Packaging (Android (ETC2)): Copying permission_library directory to staging before build
UATHelper: Packaging (Android (ETC2)): Directory C:/Program Files/Epic Games/UE_4.21/Engine/Source/ThirdParty/AndroidPermission/permission_library copied to E:/Unreal/DuelPrototype/Intermediate/Android/APK/JavaLibs/permission_library
UATHelper: Packaging (Android (ETC2)): ==== Writing new GameActivity.java file to E:\Unreal\DuelPrototype\Intermediate/Android/APK\src\com\epicgames\ue4\GameActivity.java ====
UATHelper: Packaging (Android (ETC2)): Copying new .so E:\Unreal\DuelPrototype\Binaries\Android\TheGovernor-Android-Shipping-arm64-es2.so file to jni folder...
UATHelper: Packaging (Android (ETC2)): Copying Admob Libs files to staging
UATHelper: Packaging (Android (ETC2)): File E:/Unreal/DuelPrototype/Plugins/AdCollection/Source/AdCollection/../ThirdParty/ThirdParty/Android/gradle/app/build.gradle copied to E:/Unreal/DuelPrototype/Intermediate/Android/APK/gradle/app/build.gradle
UATHelper: Packaging (Android (ETC2)): File E:/Unreal/DuelPrototype/Plugins/AdCollection/Source/AdCollection/../ThirdParty/ThirdParty/Android/externlibs/chartboost.jar copied to E:/Unreal/DuelPrototype/Intermediate/Android/APK/gradle/app/src/main/externlibs/chartboost.jar
UATHelper: Packaging (Android (ETC2)): File E:/Unreal/DuelPrototype/Plugins/AdCollection/Source/AdCollection/../ThirdParty/ThirdParty/Android/externlibs/unity-classes.jar copied to E:/Unreal/DuelPrototype/Intermediate/Android/APK/gradle/app/src/main/externlibs/unity-classes.jar
UATHelper: Packaging (Android (ETC2)): Copying libvrapi.so
UATHelper: Packaging (Android (ETC2)): File C:/Program Files/Epic Games/UE_4.21/Engine/Source/ThirdParty/Oculus/OVRPlugin/OVRPlugin/ExtLibs/arm64-v8a/libvrapi.so copied to E:/Unreal/DuelPrototype/Intermediate/Android/APK/libs/arm64-v8a/libvrapi.so
UATHelper: Packaging (Android (ETC2)): Copying libvrintegrationloader.so
UATHelper: Packaging (Android (ETC2)): File C:/Program Files/Epic Games/UE_4.21/Engine/Source/ThirdParty/Oculus/OVRPlugin/OVRPlugin/ExtLibs/arm64-v8a/libvrintegrationloader.so copied to E:/Unreal/DuelPrototype/Intermediate/Android/APK/libs/arm64-v8a/libvrintegrationloader.so
UATHelper: Packaging (Android (ETC2)): Copying libOVRPlugin.so
UATHelper: Packaging (Android (ETC2)): File C:/Program Files/Epic Games/UE_4.21/Engine/Source/ThirdParty/Oculus/OVRPlugin/OVRPlugin/Lib/arm64-v8a/libOVRPlugin.so copied to E:/Unreal/DuelPrototype/Intermediate/Android/APK/libs/arm64-v8a/libOVRPlugin.so
UATHelper: Packaging (Android (ETC2)): File C:/Program Files/Epic Games/UE_4.21/Engine/Source/ThirdParty/Oculus/OVRPlugin/OVRPlugin/ExtLibs/VrApi.jar copied to E:/Unreal/DuelPrototype/Intermediate/Android/APK/libs/VrApi.jar
UATHelper: Packaging (Android (ETC2)): File C:/Program Files/Epic Games/UE_4.21/Engine/Source/ThirdParty/Oculus/OVRPlugin/OVRPlugin/ExtLibs/SystemUtils.jar copied to E:/Unreal/DuelPrototype/Intermediate/Android/APK/libs/SystemUtils.jar
UATHelper: Packaging (Android (ETC2)): ====14.06.2019 12:50:10====PERFORMING FINAL APK PACKAGE OPERATION================================================
UATHelper: Packaging (Android (ETC2)): Fixing minSdkVersion; NDK level above 19 requires minSdkVersion of 21 (arch=arm64)
UATHelper: Packaging (Android (ETC2)): Creating rungradle.bat to work around commandline length limit (using unused drive letter Z:)
UATHelper: Packaging (Android (ETC2)): Making .apk with Gradle...
UATHelper: Packaging (Android (ETC2)): To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/4.1/userguide/gradle_daemon.html.
UATHelper: Packaging (Android (ETC2)): Exception in thread "DisconnectableInputStream source reader" org.gradle.api.UncheckedIOException: java.io.IOException: ��leyici ge�ersiz
UATHelper: Packaging (Android (ETC2)):     at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:57)
UATHelper: Packaging (Android (ETC2)):     at org.gradle.internal.UncheckedException.throwAsUncheckedException(UncheckedException.java:40)
UATHelper: Packaging (Android (ETC2)):     at org.gradle.util.DisconnectableInputStream$1.run(DisconnectableInputStream.java:125)
UATHelper: Packaging (Android (ETC2)):     at java.lang.Thread.run(Thread.java:745)
UATHelper: Packaging (Android (ETC2)): Caused by: java.io.IOException: ��leyici ge�ersiz
UATHelper: Packaging (Android (ETC2)):     at java.io.FileInputStream.readBytes(Native Method)
UATHelper: Packaging (Android (ETC2)):     at java.io.FileInputStream.read(FileInputStream.java:255)
UATHelper: Packaging (Android (ETC2)):     at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
UATHelper: Packaging (Android (ETC2)):     at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
UATHelper: Packaging (Android (ETC2)):     at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
UATHelper: Packaging (Android (ETC2)):     at org.gradle.util.DisconnectableInputStream$1.run(DisconnectableInputStream.java:96)
UATHelper: Packaging (Android (ETC2)):     ... 1 more
UATHelper: Packaging (Android (ETC2)): Daemon will be stopped at the end of the build stopping after processing
UATHelper: Packaging (Android (ETC2)): Observed package id 'build-tools;24.0.0' in inconsistent location 'C:\NVPACK\android-sdk-windows\build-tools\24.0.1' (Expected 'C:\NVPACK\android-sdk-windows\build-tools\24.0.0')
UATHelper: Packaging (Android (ETC2)): Observed package id 'build-tools;24.0.0' in inconsistent location 'C:\NVPACK\android-sdk-windows\build-tools\24.0.1' (Expected 'C:\NVPACK\android-sdk-windows\build-tools\24.0.0')
UATHelper: Packaging (Android (ETC2)): :app:preBuild UP-TO-DATE
UATHelper: Packaging (Android (ETC2)): :app:extractProguardFiles
UATHelper: Packaging (Android (ETC2)): :downloader_library:preBuild UP-TO-DATE
UATHelper: Packaging (Android (ETC2)): :downloader_library:preReleaseBuild UP-TO-DATE
UATHelper: Packaging (Android (ETC2)): :downloader_library:checkReleaseManifest
UATHelper: Packaging (Android (ETC2)): :downloader_library:processReleaseManifest
UATHelper: Packaging (Android (ETC2)): :permission_library:preBuild UP-TO-DATE
UATHelper: Packaging (Android (ETC2)): :permission_library:preReleaseBuild UP-TO-DATE
UATHelper: Packaging (Android (ETC2)): :permission_library:checkReleaseManifest
UATHelper: Packaging (Android (ETC2)): :permission_library:processReleaseManifest
UATHelper: Packaging (Android (ETC2)): :app:preReleaseBuild FAILED
UATHelper: Packaging (Android (ETC2)): FAILURE: Build failed with an exception.
UATHelper: Packaging (Android (ETC2)): * What went wrong:
UATHelper: Packaging (Android (ETC2)): Could not resolve all files for configuration ':app:releaseCompileClasspath'.
UATHelper: Packaging (Android (ETC2)): > Could not resolve com.android.volley:volley:1.1.1.
UATHelper: Packaging (Android (ETC2)):   Required by:
UATHelper: Packaging (Android (ETC2)):       project :app
UATHelper: Packaging (Android (ETC2)):    > Could not resolve com.android.volley:volley:1.1.1.
UATHelper: Packaging (Android (ETC2)):       > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/volley/volley/1.1.1/volley-1.1.1.pom'.
UATHelper: Packaging (Android (ETC2)):          > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/volley/volley/1.1.1/volley-1.1.1.pom'.
UATHelper: Packaging (Android (ETC2)):             > Connect to dl.google.com:443 [dl.google.com/172.217.19.142] failed: Connection timed out: connect
UATHelper: Packaging (Android (ETC2)):    > Could not resolve com.android.volley:volley:1.1.1.
UATHelper: Packaging (Android (ETC2)):       > Could not get resource 'https://jcenter.bintray.com/com/android/volley/volley/1.1.1/volley-1.1.1.pom'.
UATHelper: Packaging (Android (ETC2)):          > Could not GET 'https://jcenter.bintray.com/com/android/volley/volley/1.1.1/volley-1.1.1.pom'.
UATHelper: Packaging (Android (ETC2)):             > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/35.157.207.108, jcenter.bintray.com/54.93.138.218] failed: Connection timed out: connect
UATHelper: Packaging (Android (ETC2)): > Could not resolve com.facebook.android:audience-network-sdk:4.99.1.
UATHelper: Packaging (Android (ETC2)):   Required by:
UATHelper: Packaging (Android (ETC2)):       project :app
UATHelper: Packaging (Android (ETC2)):    > Could not resolve com.facebook.android:audience-network-sdk:4.99.1.
UATHelper: Packaging (Android (ETC2)):       > Could not get resource 'https://dl.google.com/dl/android/maven2/com/facebook/android/audience-network-sdk/4.99.1/audience-network-sdk-4.99.1.pom'.
UATHelper: Packaging (Android (ETC2)):          > Could not GET 'https://dl.google.com/dl/android/maven2/com/facebook/android/audience-network-sdk/4.99.1/audience-network-sdk-4.99.1.pom'.
UATHelper: Packaging (Android (ETC2)):             > Connect to dl.google.com:443 [dl.google.com/172.217.19.142] failed: Connection timed out: connect
UATHelper: Packaging (Android (ETC2)):    > Could not resolve com.facebook.android:audience-network-sdk:4.99.1.
UATHelper: Packaging (Android (ETC2)):       > Could not get resource 'https://jcenter.bintray.com/com/facebook/android/audience-network-sdk/4.99.1/audience-network-sdk-4.99.1.pom'.
UATHelper: Packaging (Android (ETC2)):          > Could not GET 'https://jcenter.bintray.com/com/facebook/android/audience-network-sdk/4.99.1/audience-network-sdk-4.99.1.pom'.
UATHelper: Packaging (Android (ETC2)):             > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/35.157.207.108, jcenter.bintray.com/54.93.138.218] failed: Connection timed out: connect
UATHelper: Packaging (Android (ETC2)): * Try:
UATHelper: Packaging (Android (ETC2)): Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
UATHelper: Packaging (Android (ETC2)): * Get more help at https://help.gradle.org
UATHelper: Packaging (Android (ETC2)): BU�LD FAILED in 1m 9s
UATHelper: Packaging (Android (ETC2)): 6 actionable tasks: 6 executed
UATHelper: Packaging (Android (ETC2)): ERROR: cmd.exe failed with args /c "E:\Unreal\DuelPrototype\Intermediate/Android/APK\gradle\rungradle.bat" :app:assembleRelease
UATHelper: Packaging (Android (ETC2)):        (see C:\Users\desertfish\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_4.21\Log.txt for full exception trace)
PackagingResults: Error: cmd.exe failed with args /c "E:\Unreal\DuelPrototype\Intermediate/Android/APK\gradle\rungradle.bat" :app:assembleRelease
UATHelper: Packaging (Android (ETC2)): AutomationTool exiting with ExitCode=1 (Error_Unknown)
UATHelper: Packaging (Android (ETC2)): BUILD FAILED

Im getting this error unreal 4.21

**Comment by feixuwu** [comment]
seems your network have problem, can not Download depend library

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by okanerenli** [comment]
yes i found that fire wall was stopping it. Now i can get clean build when i try to use the application. there is error..
![Screenshot_20190614-183345](https://user-images.githubusercontent.com/44051421/59520640-139fe380-8ed3-11e9-912c-a82616251a9e.png)

**Comment by feixuwu** [comment]
Please delete the intermediate folder, then reopen the project, and then do a full rebuild package.
If u still have problem, please let me know

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: okanerenli <notifications@github.com>
发送时间: Friday, June 14, 2019 11:35:08 PM
收件人: feixuwu/UnrealEngine4-EZ-Mobile-Ads
抄送: xufeiwu; Comment
主题: Re: [feixuwu/UnrealEngine4-EZ-Mobile-Ads] Unreal android package fail (#21)


yes i found that fire wall was stopping it. Now i can get clean build when i try to use the application. there is error..
[Screenshot_20190614-183345]<https://user-images.githubusercontent.com/44051421/59520640-139fe380-8ed3-11e9-912c-a82616251a9e.png>

―

**Comment by okanerenli** [comment]
you were right again :) . And your plugin working perfectly: I  managed to get admob interstitial test thanks to you. And thanks a lot!
