### ISSUE TITLE
Problems while building aab over android studio

### ISSUE THREAD

**Issue by omrumcetin** [feixuwu/UnrealEngine4-EZ-Mobile-Ads#24]
Hi,
I have decided to use your plugin, github version, while debugging in android studio I have 2 errors, related with object constructing and calling InitAdMob has different length in class.

In GameActivity java they are called as follows.
```java
//this line below
adMobInstance = new AdMob(this, activityLayout, false, false); //this line
final String app_id = _bundle.getString("com.epicgames.ue4.AdMob.AppId");
final String adBannerUnit = _bundle.getString("com.epicgames.ue4.AdMob.BannerAdUnit");
final String interstitialUnit = _bundle.getString("com.epicgames.ue4.AdMob.InterstitialAdUnit");
final String adRewardedUnit = _bundle.getString("com.epicgames.ue4.AdMob.RewardedVideoAdUnit");
//this line below
adMobInstance.InitAdMob(app_id, adBannerUnit, interstitialUnit, adRewardedUnit);
Log.debug("AdMob:InitFinish:" + app_id + " " + adBannerUnit + " " + interstitialUnit + " " + adRewardedUnit);
```

But in AdMob.java your constructors are
```java
public AdMob(Activity activity, LinearLayout mainLayout, boolean isForUnity)

public void InitAdMob(String AppId, String adBannerUnit, String interstitialUnit, String rewardUnit, String testDevice)
```

**Comment by feixuwu** [comment]
which engine version and plugin version u use? would u please post the package error?

获取 Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by omrumcetin** [comment]
unreal 4.24,
I found the problem, I installed first one of your plugin from marketplace. For the test I removed your marketplace version and placed github version. It throw above error. 
Then deleted intermediate folder and tried again.
Now its working.
Nothing to bother.

Extra question:
Does your plugin forces to permissions like WRITE_EXTERNAL_STORAGE and READ_EXTERNAL_STORAGE?
