### ISSUE TITLE
UE 4.19 Support?

### ISSUE THREAD

**Issue by shukenmg** [feixuwu/UnrealEngine4-EZ-Mobile-Ads#4]

**Comment by shukenmg** [comment]
I have these errors when i package for IOS on on 4.19

`UATHelper: Packaging (iOS):   LogInit: Display: LogProperty: Error: UStructProperty::Serialize Loading: Property 'StructProperty /Game/Widget/MainMenu.MainMenu_C:OnSuccess_02863730450899D9E15884ADF8D353FE.RewardStatus'. Unknown structure.
UATHelper: Packaging (iOS):   LogInit: Display: LogProperty: Error: UStructProperty::Serialize Loading: Property 'StructProperty /Game/Widget/MainMenu.MainMenu_C:OnSuccess_D5E3FD6F424A7773A7EF83AA272DB2C6.RewardStatus'. Unknown structure.
UATHelper: Packaging (iOS):   LogInit: Display: LogProperty: Error: UStructProperty::Serialize Loading: Property 'StructProperty /Game/Widget/MainMenu.MainMenu_C:OnSuccess_D6923B6C412EE2CEB765D7A46F341AF3.RewardStatus'. Unknown structure.
UATHelper: Packaging (iOS):   LogInit: Display: LogProperty: Error: UStructProperty::Serialize Loading: Property 'StructProperty /Game/Widget/MainMenu.MainMenu_C:ExecuteUbergraph_MainMenu.K2Node_CustomEvent_RewardStatus3'. Unknown structure.
UATHelper: Packaging (iOS):   LogInit: Display: LogProperty: Error: UStructProperty::Serialize Loading: Property 'StructProperty /Game/Widget/MainMenu.MainMenu_C:ExecuteUbergraph_MainMenu.Temp_struct_Variable'. Unknown structure.
UATHelper: Packaging (iOS):   LogInit: Display: LogProperty: Error: UStructProperty::Serialize Loading: Property 'StructProperty /Game/Widget/MainMenu.MainMenu_C:ExecuteUbergraph_MainMenu.K2Node_CustomEvent_RewardStatus2'. Unknown structure.
UATHelper: Packaging (iOS):   LogInit: Display: LogProperty: Error: UStructProperty::Serialize Loading: Property 'StructProperty /Game/Widget/MainMenu.MainMenu_C:ExecuteUbergraph_MainMenu.Temp_struct_Variable2'. Unknown structure.
UATHelper: Packaging (iOS):   LogInit: Display: LogProperty: Error: UStructProperty::Serialize Loading: Property 'StructProperty /Game/Widget/MainMenu.MainMenu_C:ExecuteUbergraph_MainMenu.K2Node_CustomEvent_RewardStatus'. Unknown structure.
UATHelper: Packaging (iOS):   LogInit: Display: LogProperty: Error: UStructProperty::Serialize Loading: Property 'StructProperty /Game/Widget/MainMenu.MainMenu_C:ExecuteUbergraph_MainMenu.Temp_struct_Variable3'. Unknown structure.
UATHelper: Packaging (iOS):   LogInit: Display: LogBlueprint: Error: ProxyFactoryClass null in K2Node_AsyncAction /Game/Widget/MainMenu.MainMenu:EventGraph.K2Node_AsyncAction_0. Was a class deleted or saved on a non promoted build?
UATHelper: Packaging (iOS):   LogInit: Display: LogBlueprint: Error: ProxyFactoryClass null in K2Node_AsyncAction /Game/Widget/MainMenu.MainMenu:EventGraph.K2Node_AsyncAction_7. Was a class deleted or saved on a non promoted build?
UATHelper: Packaging (iOS):   LogInit: Display: LogBlueprint: Error: ProxyFactoryClass null in K2Node_AsyncAction /Game/Widget/MainMenu.MainMenu:EventGraph.K2Node_AsyncAction_12. Was a class deleted or saved on a non promoted build?
UATHelper: Packaging (iOS):   LogInit: Display: LogBlueprint: Error: [Compiler MainMenu] BaseAsyncTask: Missing function PlayRewardedVideo from class Unknown Class for async task  Async Task: Missing Function from Source: /Game/Widget/MainMenu.MainMenu
UATHelper: Packaging (iOS):   LogInit: Display: LogBlueprint: Error: [Compiler MainMenu] In use pin  <Unnamed>  no longer exists on node  Show Interstitial . Please refresh node or break links to remove pin. from Source: /Game/Widget/MainMenu.MainMenu
UATHelper: Packaging (iOS):   LogInit: Display: LogBlueprint: Error: [Compiler MainMenu] Could not find a function named "ShowInterstitial" in 'MainMenu'.
UATHelper: Packaging (iOS):   Make sure 'MainMenu' has been compiled for  Show Interstitial from Source: /Game/Widget/MainMenu.MainMenu
UATHelper: Packaging (iOS):   LogInit: Display: LogBlueprint: Error: [Compiler MainMenu] In use pin  <Unnamed>  no longer exists on node  Show Banner . Please refresh node or break links to remove pin. from Source: /Game/Widget/MainMenu.MainMenu
UATHelper: Packaging (iOS):   LogInit: Display: LogBlueprint: Error: [Compiler MainMenu] Could not find a function named "ShowBanner" in 'MainMenu'.
UATHelper: Packaging (iOS):   Make sure 'MainMenu' has been compiled for  Show Banner from Source: /Game/Widget/MainMenu.MainMenu
UATHelper: Packaging (iOS):   LogInit: Display: LogBlueprint: Error: [Compiler MainMenu] In use pin  <Unnamed>  no longer exists on node  Play Ad Video . Please refresh node or break links to remove pin. from Source: /Game/Widget/MainMenu.MainMenu
UATHelper: Packaging (iOS):   LogInit: Display: LogBlueprint: Error: [Compiler MainMenu] Could not find a function named "PlayAdVideo" in 'MainMenu'.
UATHelper: Packaging (iOS):   Make sure 'MainMenu' has been compiled for  Play Ad Video from Source: /Game/Widget/MainMenu.MainMenu
UATHelper: Packaging (iOS):   LogInit: Display: LogBlueprint: Error: [Compiler MainMenu] In use pin  Reward Status  no longer exists on node  Async Task: Missing Function . Please refresh node or break links to remove pin. from Source: /Game/Widget/MainMenu.MainMenu
UATHelper: Packaging (iOS):   LogInit: Display: LogBlueprint: Error: [Compiler MainMenu] Could not find a function named "PlayRewardedVideo" in 'MainMenu'.
UATHelper: Packaging (iOS):   Make sure 'MainMenu' has been compiled for  Async Task: Missing Function from Source: /Game/Widget/MainMenu.MainMenu
UATHelper: Packaging (iOS):   LogInit: Display: LogBlueprint: Error: [Compiler MainMenu] In use pin  Return Value  no longer exists on node  Is Rewarded Video Ready . Please refresh node or break links to remove pin. from Source: /Game/Widget/MainMenu.MainMenu
UATHelper: Packaging (iOS):   LogInit: Display: LogBlueprint: Error: [Compiler MainMenu] Could not find a function named "IsRewardedVideoReady" in 'MainMenu'.
UATHelper: Packaging (iOS):   Make sure 'MainMenu' has been compiled for  Is Rewarded Video Ready from Source: /Game/Widget/MainMenu.MainMenu
UATHelper: Packaging (iOS):   LogInit: Display: LogBlueprint: Error: [Compiler MainMenu] In use pin  Return Value  no longer exists on node  Is Banner Ready . Please refresh node or break links to remove pin. from Source: /Game/Widget/MainMenu.MainMenu
UATHelper: Packaging (iOS):   LogInit: Display: LogBlueprint: Error: [Compiler MainMenu] Could not find a function named "IsBannerReady" in 'MainMenu'.
UATHelper: Packaging (iOS):   Make sure 'MainMenu' has been compiled for  Is Banner Ready from Source: /Game/Widget/MainMenu.MainMenu
UATHelper: Packaging (iOS):   LogInit: Display: LogBlueprint: Error: [Compiler MainMenu] In use pin  Return Value  no longer exists on node  Is Interstitial Ready . Please refresh node or break links to remove pin. from Source: /Game/Widget/MainMenu.MainMenu
UATHelper: Packaging (iOS):   LogInit: Display: LogBlueprint: Error: [Compiler MainMenu] Could not find a function named "IsInterstitialReady" in 'MainMenu'.
UATHelper: Packaging (iOS):   Make sure 'MainMenu' has been compiled for  Is Interstitial Ready from Source: /Game/Widget/MainMenu.MainMenu
UATHelper: Packaging (iOS):   LogInit: Display: LogBlueprint: Error: [Compiler MainMenu] Unexpected node type K2Node_AsyncAction encountered at  Async Task: Missing Function from Source: /Game/Widget/MainMenu.MainMenu
UATHelper: Packaging (iOS):   LogInit: Display: LogPluginManager: Warning: Plugin 'AdCollection' is not compatible with the current engine version (4.18.0)
UATHelper: Packaging (iOS):   LogInit: Display: LogLinker: Warning: Can't find file '/Script/AdCollection'
UATHelper: Packaging (iOS):   LogInit: Display: LogUObjectGlobals: Warning: Failed to load '/Script/AdCollection': Can't find file '/Script/AdCollection'
UATHelper: Packaging (iOS):   LogInit: Display: LogLinker: Warning: Can't find file for asset '/Script/AdCollection' while loading ../../../../../../Desktop/UnrealEngine4-EZ-Mobile-Ads-master/Content/Widget/MainMenu.uasset.
UATHelper: Packaging (iOS):   LogInit: Display: LogUObjectGlobals: Warning: Failed to load '../../../../../../Desktop/UnrealEngine4-EZ-Mobile-Ads-master/Content/Widget/MainMenu.uasset': Can't find file for asset '/Script/AdCollection' while loading ../../../../../../Desktop/UnrealEngine4-EZ-Mobile-Ads-master/Content/Widget/MainMenu.uasset.
UATHelper: Packaging (iOS):   LogInit: Display: LogLinker: Warning: Can't find file for asset '/Script/AdCollection' while loading ../../../../../../Desktop/UnrealEngine4-EZ-Mobile-Ads-master/Content/Map/ShowCase.umap.
UATHelper: Packaging (iOS):   LogInit: Display: LogUObjectGlobals: Warning: Failed to load '../../../../../../Desktop/UnrealEngine4-EZ-Mobile-Ads-master/Content/Map/ShowCase.umap': Can't find file for asset '/Script/AdCollection' while loading ../../../../../../Desktop/UnrealEngine4-EZ-Mobile-Ads-master/Content/Map/ShowCase.umap.
UATHelper: Packaging (iOS):   LogInit: Display: LogBlueprint: Warning: [Compiler MainMenu] Input pin  Ad Type  specifying non-default value no longer exists on node  Async Task: Missing Function . Please refresh node or reset pin to default value to remove pin.
UATHelper: Packaging (iOS):   LogInit: Display: LogBlueprint: Warning: [Compiler MainMenu] Node  Async Task: Missing Function . The node won't be pruned as isolated one. The node is not pure, but it has no exec pin(s). Verify IsNodePure implementation in K2Node Call Function.
UATHelper: Packaging (iOS):   LogInit: Display: LogBlueprint: Warning: [Compiler MainMenu] [0010.73] Compile of MainMenu failed. 58 Fatal Issue(s) 4 Warning(s) [in 12 ms] (/Game/Widget/MainMenu.MainMenu)`

**Comment by feixuwu** [comment]
4.19 preview?
I will take time to check it

**Comment by shukenmg** [comment]
Thank you for your help :)

**Comment by shukenmg** [comment]
Do you have some progress on this?

**Comment by feixuwu** [comment]
hi, I have submit the change, it should fix the packaging problem.
