### ISSUE TITLE
IOS Rewarded Video

### ISSUE THREAD

**Issue by shukenmg** [feixuwu/UnrealEngine4-EZ-Mobile-Ads#6]
But now i have a new problem with IOS Admob rewarded video.
It does not fire success.
Android does not have this problem.

**Comment by feixuwu** [comment]
Hi, thanks for your reply, several question:

1、 Did you fill the right ad unit id? Android ad unit is not the same as IOS ad unit., you need to create ad unit for ios.

2、 Did you set the eCPM limit (for example, only show eCPM over 0.5$)?
By the way, admob rewarded video ad is not available on every country or region.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: shukenmg <notifications@github.com>
发送时间: Friday, April 27, 2018 1:48:48 PM
收件人: feixuwu/UnrealEngine4-EZ-Mobile-Ads
抄送: Subscribed
主题: [feixuwu/UnrealEngine4-EZ-Mobile-Ads] IOS Rewarded Video (#6)


But now i have a new problem with IOS Admob rewarded video.
It does not fire success.
Android does not have this problem.

―

**Comment by shukenmg** [comment]
Hi
Thanks for your answer 

For your first question
 I put the correct ad id because the video plays but when it finishes it does not return success.
 
2
 I did not put a eCPM limit.

So to recap
 The video AD plays but it does not return success 

Thanks for your help.

**Comment by shukenmg** [comment]
Hi @feixuwu 
Thanks for your answer 

For your first question
 I put the correct ad id because the video plays but when it finishes it does not return success.
 
2
 I did not put a eCPM limit.

So to recap
 The video AD plays but it does not return success 

Thanks for your help.

**Comment by feixuwu** [comment]
sorry about the delay, I will check this problem this weekend.

?? Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by feixuwu** [comment]
hi, I tested on my iphone device, this bug is not exist, you need to watch the rewarded video complete and then it will call the callback, please note only rewarded video will call the call back, you can test it on my demo project, after you wath the rewarded video ads complete, it will print a message.
To learn how to use the function, please read the readme or the demo project.

**Comment by shukenmg** [comment]
I tested on my iphone and it does not call the callback

I am using the admob advanced version tho
Maybe that's the problem?

Thanks.

**Comment by feixuwu** [comment]
I will take time to check it this weekend, thanks very much

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: shukenmg <notifications@github.com>
发送时间: Friday, May 25, 2018 8:41:25 PM
收件人: feixuwu/UnrealEngine4-EZ-Mobile-Ads
抄送: xufeiwu; Mention
主题: Re: [feixuwu/UnrealEngine4-EZ-Mobile-Ads] IOS Rewarded Video (#6)


I tested on my iphone and it does not call the callback

I am using the admob advanced version tho
Maybe that's the problem?

Thanks.

―

**Comment by feixuwu** [comment]
Hi, thanks for your reply, I upgrade my admob to new version, and it does not callback after finish watch ads.
I upgraded the admob sdk for IOS and fixed the bug, please clone the latest plugin and replace with it.


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: shukenmg <notifications@github.com>
发送时间: Friday, May 25, 2018 8:41:25 PM
收件人: feixuwu/UnrealEngine4-EZ-Mobile-Ads
抄送: xufeiwu; Mention
主题: Re: [feixuwu/UnrealEngine4-EZ-Mobile-Ads] IOS Rewarded Video (#6)


I tested on my iphone and it does not call the callback

I am using the admob advanced version tho
Maybe that's the problem?

Thanks.

―

**Comment by shukenmg** [comment]
@feixuwu 

Why are some ad networks removed?

**Comment by feixuwu** [comment]
Yes, I removed Vungle, vungle ios sdk changed a lot, use the latest vungle sdk, I need change the editor. I have no too much time to work with this.
And there’s very few people use vungle, so I removed vungle.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: shukenmg <notifications@github.com>
发送时间: Sunday, May 27, 2018 4:15:28 PM
收件人: feixuwu/UnrealEngine4-EZ-Mobile-Ads
抄送: xufeiwu; Mention
主题: Re: [feixuwu/UnrealEngine4-EZ-Mobile-Ads] IOS Rewarded Video (#6)


@feixuwu<https://github.com/feixuwu>

Why are some ad networks removed?

―

**Comment by feixuwu** [comment]
You use https://github.com/feixuwu/UnrealEngine4-Admob?

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: shukenmg <notifications@github.com>
发送时间: Sunday, May 27, 2018 4:22:22 PM
收件人: feixuwu/UnrealEngine4-EZ-Mobile-Ads
抄送: xufeiwu; Mention
主题: Re: [feixuwu/UnrealEngine4-EZ-Mobile-Ads] IOS Rewarded Video (#6)


@feixuwu<https://github.com/feixuwu>
Ok, but i have a problem, i ues meditation on admob so I need to use the admob advance version.
So i still have problem there.

I also use vungle with admob meditation

―

**Comment by shukenmg** [comment]
Exactly 
@feixuwu

**Comment by feixuwu** [comment]
Then you can try replace the AdsUtil.embeddedframework.zip with the latest version from https://github.com/feixuwu/UnrealEngine4-EZ-Mobile-Ads.
I did not tested, but it should solve your problem.

If it does not work, please let me know.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: shukenmg <notifications@github.com>
发送时间: Sunday, May 27, 2018 4:42:00 PM
收件人: feixuwu/UnrealEngine4-EZ-Mobile-Ads
抄送: xufeiwu; Mention
主题: Re: [feixuwu/UnrealEngine4-EZ-Mobile-Ads] IOS Rewarded Video (#6)


Exactly
@feixuwu<https://github.com/feixuwu>

―

**Comment by shukenmg** [comment]
Ok I will test It
Thank you very much @feixuwu for your active help, I appreciate it very much 😃

**Comment by shukenmg** [comment]
@feixuwu 
非常謝謝您的幫忙

**Comment by shukenmg** [comment]
我會儘快測試。

**Comment by shukenmg** [comment]
@feixuwu May I ask how I can deal with GDPR?

**Comment by feixuwu** [comment]
I have no too much information about this currently.
I think the developer will not affect too much if you just use admob. but I really know little about it.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: shukenmg <notifications@github.com>
发送时间: Sunday, May 27, 2018 5:05:57 PM
收件人: feixuwu/UnrealEngine4-EZ-Mobile-Ads
抄送: xufeiwu; Mention
主题: Re: [feixuwu/UnrealEngine4-EZ-Mobile-Ads] IOS Rewarded Video (#6)


@feixuwu<https://github.com/feixuwu> May I ask how I can deal with GDPR?

―

**Comment by shukenmg** [comment]
@feixuwu 
Ok i have done some tests

the new AdsUtil.embeddedframework.zip fixes the problem in ue4 4.18,
but the problem is still there in 4.19.2

thanks

**Comment by shukenmg** [comment]
@feixuwu 
Thank you for all your hard work.
The problem is fixed now.

Thank you again.
